#!/bin/bash

[ -z "$PHASHDB" ] && PHASHDB="$HOME/.phashdb"

while getopts '+hd:' opt; do
    case $opt in
        h)
            echo "Usage: $0 [-d DB_DIR] [-h]"
            echo
            echo "  -d DB_DIR"
            echo "    Specify directory to use for the database." \
                 "(default: \$PHASHDB or \$HOME/.phashdb)"
            echo
            echo "  -h"
            echo "    Display this message and exit."
            echo
            exit
            ;;
        d)
            PHASHDB="$OPTARG"
            ;;
    esac
done

if [ -f "$PHASHDB/.pid" ]; then
    DPID=$(cat "$PHASHDB/.pid")
    if kill -0 "$DPID" 2>/dev/null && \
       [ "$(cat /proc/$DPID/comm)" == "phashd" ]; then
        echo "Stopping phashd."
        kill "$DPID"
    fi
fi

rm -r "$PHASHDB" && echo "Done."
